In [1]:
%matplotlib inline


What is PyTorch?
================

It’s a Python based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

### Tensors

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [2]:
import torch

Construct a 5x3 matrix, uninitialized:



In [3]:
x = torch.empty(5, 3)
# print(x)

Construct a randomly initialized matrix:



In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[ 0.6189,  0.6762,  0.5095],
        [ 0.9384,  0.8075,  0.9736],
        [ 0.5650,  0.0112,  0.4283],
        [ 0.4183,  0.7892,  0.6768],
        [ 0.7936,  0.8549,  0.8061]])


Construct a matrix filled zeros and of dtype long:



In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


Construct a tensor directly from data:



In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([ 5.5000,  3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)
tensor([[ 0.0485, -3.9217,  0.7751],
        [ 0.3954,  0.8411, -0.2672],
        [-1.3806,  1.5067,  1.3811],
        [ 0.0250,  0.7954, -0.2672],
        [-0.3297,  0.3593, -0.1558]])


Get its size:



In [8]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

### Operations

There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.6128, -3.8307,  1.2781],
        [ 0.8017,  1.5061,  0.4103],
        [-0.8920,  1.6882,  2.3250],
        [ 0.2541,  0.8011,  0.5007],
        [ 0.6597,  0.4792,  0.6479]])


Addition: syntax 2



In [10]:
print(torch.add(x, y))

tensor([[ 0.6128, -3.8307,  1.2781],
        [ 0.8017,  1.5061,  0.4103],
        [-0.8920,  1.6882,  2.3250],
        [ 0.2541,  0.8011,  0.5007],
        [ 0.6597,  0.4792,  0.6479]])


Addition: providing an output tensor as argument



In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.6128, -3.8307,  1.2781],
        [ 0.8017,  1.5061,  0.4103],
        [-0.8920,  1.6882,  2.3250],
        [ 0.2541,  0.8011,  0.5007],
        [ 0.6597,  0.4792,  0.6479]])


Addition: in-place



In [12]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.6128, -3.8307,  1.2781],
        [ 0.8017,  1.5061,  0.4103],
        [-0.8920,  1.6882,  2.3250],
        [ 0.2541,  0.8011,  0.5007],
        [ 0.6597,  0.4792,  0.6479]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [13]:
x

tensor([[ 0.0485, -3.9217,  0.7751],
        [ 0.3954,  0.8411, -0.2672],
        [-1.3806,  1.5067,  1.3811],
        [ 0.0250,  0.7954, -0.2672],
        [-0.3297,  0.3593, -0.1558]])

In [14]:
x[1, :]

tensor([ 0.3954,  0.8411, -0.2672])

In [15]:
x[:, 1]

tensor([-3.9217,  0.8411,  1.5067,  0.7954,  0.3593])

Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [16]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [17]:
x

tensor([[-1.4648, -0.7016, -0.2893,  1.0716],
        [ 0.1805, -0.2815,  0.5367, -2.2606],
        [ 0.2819, -0.7389, -0.8246,  0.2005],
        [-0.6512,  0.3151, -0.4426, -0.4337]])

In [18]:
y

tensor([-1.4648, -0.7016, -0.2893,  1.0716,  0.1805, -0.2815,  0.5367,
        -2.2606,  0.2819, -0.7389, -0.8246,  0.2005, -0.6512,  0.3151,
        -0.4426, -0.4337])

In [19]:
z

tensor([[-1.4648, -0.7016, -0.2893,  1.0716,  0.1805, -0.2815,  0.5367,
         -2.2606],
        [ 0.2819, -0.7389, -0.8246,  0.2005, -0.6512,  0.3151, -0.4426,
         -0.4337]])

If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [20]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.7921])
-1.7920788526535034


<div class="alert alert-info"><h4>Note</h4><p>
``torch.rand()`` for uniform distribution; ``torch.randn()`` for normal distribution.
</p></div>

**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  [here](http://pytorch.org/docs/torch).

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

### Converting a Torch Tensor to a NumPy Array



In [21]:
a = torch.ones(5)
print(a)

tensor([ 1.,  1.,  1.,  1.,  1.])


In [22]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [23]:
a.add_(1)
print(a)
print(b)

tensor([ 2.,  2.,  2.,  2.,  2.])
[2. 2. 2. 2. 2.]


### Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically



In [24]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [25]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!